/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Yan
 */
public class fmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fmPrincipal
     */
    public fmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jCadPac = new javax.swing.JButton();
        jSair = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        iaUsuario = new javax.swing.JLabel();
        iaData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jPaciente = new javax.swing.JMenuItem();
        jAnamnese = new javax.swing.JMenuItem();
        jSessoes = new javax.swing.JMenuItem();
        jProcessos = new javax.swing.JMenu();
        jAgendamento = new javax.swing.JMenuItem();
        jConfig = new javax.swing.JMenu();
        jCadPsi = new javax.swing.JMenuItem();
        jRelatorio = new javax.swing.JMenu();
        jHistClic = new javax.swing.JMenuItem();
        jHelp = new javax.swing.JMenu();
        jSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Consultório Psicologia");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jCadPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/People-32.png"))); // NOI18N
        jCadPac.setToolTipText("Cadastrar Paciente");
        jCadPac.setFocusable(false);
        jCadPac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCadPac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadPacActionPerformed(evt);
            }
        });
        jToolBar1.add(jCadPac);

        jSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Exit-32.png"))); // NOI18N
        jSair.setToolTipText("Sair");
        jSair.setFocusable(false);
        jSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jToolBar1.add(jSair);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        iaUsuario.setText("Bem vindo");

        iaData.setText("Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(iaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addComponent(iaData)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iaUsuario)
                    .addComponent(iaData))
                .addContainerGap())
        );

        jCadastro.setText("Cadastros");

        jPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jPaciente.setText("Pacientes");
        jPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPacienteActionPerformed(evt);
            }
        });
        jCadastro.add(jPaciente);

        jAnamnese.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jAnamnese.setText("Anamnese");
        jAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnamneseActionPerformed(evt);
            }
        });
        jCadastro.add(jAnamnese);

        jSessoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSessoes.setText("Sessões");
        jSessoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSessoesActionPerformed(evt);
            }
        });
        jCadastro.add(jSessoes);

        jMenuBar1.add(jCadastro);

        jProcessos.setText("Processos");

        jAgendamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jAgendamento.setText("Agendamento");
        jAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgendamentoActionPerformed(evt);
            }
        });
        jProcessos.add(jAgendamento);

        jMenuBar1.add(jProcessos);

        jConfig.setText("Configurações");

        jCadPsi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jCadPsi.setText("Cadastrar Psicólogo");
        jCadPsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadPsiActionPerformed(evt);
            }
        });
        jConfig.add(jCadPsi);

        jMenuBar1.add(jConfig);

        jRelatorio.setText("Relatórios");

        jHistClic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jHistClic.setText("Histórico Clínico");
        jHistClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHistClicActionPerformed(evt);
            }
        });
        jRelatorio.add(jHistClic);

        jMenuBar1.add(jRelatorio);

        jHelp.setText("Ajuda");

        jSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jSobre.setText("Sobre");
        jSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSobreActionPerformed(evt);
            }
        });
        jHelp.add(jSobre);

        jMenuBar1.add(jHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(203, 203, 203))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPacienteActionPerformed
        // TODO add your handling code here:
        fmPaciente paciente = new fmPaciente();
        jDesktopPane1.add(paciente);
        paciente.setVisible(true);
    }//GEN-LAST:event_jPacienteActionPerformed

    private void jAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnamneseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAnamneseActionPerformed

    private void jSessoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSessoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSessoesActionPerformed

    private void jAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgendamentoActionPerformed

    private void jCadPsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadPsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCadPsiActionPerformed

    private void jHistClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHistClicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHistClicActionPerformed

    private void jSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSobreActionPerformed
        // TODO add your handling code here:
        fmSobre sobre = new fmSobre();
        jDesktopPane1.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_jSobreActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Sistema de Prontuários Médicos",1);
        if(valor==0) System.exit(0);
        
    }//GEN-LAST:event_jSairActionPerformed

    private String mostrarData() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        
        Date date = new Date();
        return dateFormat.format(date);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                iaData.setText(mostrarData());
                
                ActionListener updater = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        iaData.setText(mostrarData());
                    }                 
                };
                Timer timer = new Timer(1000, updater);
                timer.start();
                
                this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadPacActionPerformed
        // TODO add your handling code here:
        fmPaciente paciente = new fmPaciente();
        jDesktopPane1.add(paciente);
        paciente.setVisible(true);
    }//GEN-LAST:event_jCadPacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iaData;
    private javax.swing.JLabel iaUsuario;
    private javax.swing.JMenuItem jAgendamento;
    private javax.swing.JMenuItem jAnamnese;
    private javax.swing.JButton jCadPac;
    private javax.swing.JMenuItem jCadPsi;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenu jConfig;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jHelp;
    private javax.swing.JMenuItem jHistClic;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jProcessos;
    private javax.swing.JMenu jRelatorio;
    private javax.swing.JButton jSair;
    private javax.swing.JMenuItem jSessoes;
    private javax.swing.JMenuItem jSobre;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
